In [3]:
import os
os.chdir("../..")
from src.data_import import get_instance
import dtale

/Users/saraabreu/Desktop/REPOS/PRJT1/data/data.xlsx

In [4]:
operator_information = get_instance(1,"Opt_Par")
operator_information

   Shift  Duration(min)  Setup_teams  Log_train(packs/hour)  Operators
0      1            480            1                    120         30
1      2            480            2                    120         30
2      3            480            1                    120         30

In [5]:
init_data = get_instance(1,"Init_data")
init_data

             Part  Prod_time   Machine      Tool  Nb_Operator  Packs_hour
0   F04916008001B          0   00K8004   MO.9163          1.0    9.750000
1   F04916017001A        110   00K8003   MO.9288          3.0    8.888889
2   F04916006001B          0  00K50010   MO.9162          2.0    7.500000
3   I05415065001A          0   00K3509   MO.8657          0.5    2.556818
4   I02717004001A          0   00K2006   MO.9620          0.5    1.277778
5   F02813002007A          0  00K16001   MO.7955          2.0    5.250000
6   I03306112010A          0  00K10006   MO.6694          2.0    0.833333
7   F04916023001A          0   00E8007   MO.9293          1.0    0.795455
8   F02917008003A          0   00E8006   MO.9416          1.5    4.400000
9   F02917002004A          0   00E8005   MO.9413          1.5    3.666667
10  F05115010003A          0   00E8004   MO.8569          1.5    4.200000
11  I05415162001A          0   00E6004   MO.8613          2.0   10.000000
12  F02917010004A          0   00E4005   MO.9417          1.5    0.265625
13  I02010025017A          0  00E40011   MO.7377          1.0    1.094340
14  F01620010001A        600  00E40010  MO.10212          1.0    5.222222
15  F05115007006A          0   00E3009   MO.8570          1.5    0.347222
16  I02917023002A          0   00E3008   MO.9421          2.0    9.166667
17  I00412013001A          0   00E3007   MO.7822          1.0    8.083333
18  F04916074001B        250   00E3006   MO.9886          1.0    6.666667
19  I04916034001A          0   00E2759  MO.10032          1.0    1.272727
20  F04916070001B          0  00E27510   MO.9457          0.5    3.000000
21  F04916019001A          0  00E17006   MO.9290          2.0    2.400000
22  F04916026002A          0  00E15007   MO.9298          2.0    4.187500
23  F05016004002A          0  00E15006   MO.9146          2.0    5.600000
24  F04916080001D          0  00E15005   MO.9709          2.0    2.533333
25  F02717006001A         50  00E11007   MO.9437          2.0    5.615385
26  F04916030002A          0  00E11006   MO.9301          2.0    5.714286
27  F03315003007A          0  00E11004   MO.8539          3.0    3.625000
28  F04016050001A          0  00SD1100   MO.9212          2.0    2.555556
29  F04016062003A          0   00K5009   MO.9558          2.0    3.250000
30  F01906007016A          0  00K50011   MO.6610          2.0    0.807018
31  F04016101001A          0  00K10001   MO.9204          1.0    5.000000

In [6]:
inst_data = get_instance(1,"Inst_data")
inst_data

             Part  Proc_time(min)   Machine     Tool  Nb_Operator  Packs_hour
0   F03315003007A             695  00E11004  MO.8539          3.0        3.63
1   F03315003007C             447  00E11004  MO.8539          3.0        6.44
2   F03315004005A             182  00E11004  MO.8540          3.0        3.63
3   F04916030002A             756  00E11006  MO.9301          2.0        5.71
4   F02717006001A             797  00E11007  MO.9437          2.0        5.62
..            ...             ...       ...      ...          ...         ...
67  F04916015002A             365   00K8003  MO.9288          3.0        8.89
68  F04916017001A              61   00K8003  MO.9288          3.0        8.89
69  F04916008001B             736   00K8004  MO.9163          1.0        9.75
70  F04916009001F              62   00K8004  MO.9163          1.0        9.75
71  F04916023001A             743   00E8007  MO.9293          1.0        0.80

[72 rows x 6 columns]

In [7]:
setup_data = get_instance(1,"Setup_data")
setup_data

,Setup(min),MO.10013,MO.10032,MO.10212,MO.10221,MO.10294,MO.10328,MO.10423,MO.10424,MO.10425,...,MO.9983,MO.9986,MO.9987,MO.9988,MO.9989,MO.9997,MO.IP 172,MO.IP 199,MO.IP 98,MO.SP 5171
0,MO.10013,0,38,41,48,41,45,46,45,32,...,33,40,31,37,40,43,44,34,48,50
1,MO.10032,45,0,45,30,30,41,39,35,50,...,48,46,40,47,46,36,37,40,47,36
2,MO.10212,41,34,0,41,32,31,33,44,35,...,50,34,38,35,46,46,39,32,33,50
3,MO.10221,47,41,48,0,44,31,44,33,34,...,41,41,43,46,46,36,44,42,48,40
4,MO.10294,30,44,43,36,0,36,44,46,35,...,34,39,31,42,49,42,39,42,47,42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
393,MO.9997,44,41,33,46,48,49,44,36,41,...,49,37,34,44,44,0,46,30,31,42
394,MO.IP 172,32,35,48,30,30,38,49,49,48,...,41,46,45,32,35,34,0,36,50,44
395,MO.IP 199,42,43,37,41,33,38,35,48,38,...,41,37,48,36,50,35,34,0,50,41
396,MO.IP 98,37,47,40,35,49,42,50,40,30,...,35,32,41,39,50,47,33,38,0,48
397,MO.SP 5171,41,38,39,48,45,42,31,48,37,...,38,49,36,31,38,40,37,37,38,0

In [8]:
import pandas as pd

# inst_data = get_instance(1,"Inst_data")
# inst_data
solution = pd.DataFrame(columns=["Timestamp", "Part", "OperatorID"])
solution["Part"] = ["F03315003007A"]
solutions_yield = inst_data.where(inst_data["Part"] == solution["Part"]).sum() # the sum of packs_hour according to solution
solutions_yield

ValueError: Can only compare identically-labeled Series objects

# Coisas que fazem sentido

In [21]:
import pandas as pd
import openpyxl
import tempfile


data_wb = openpyxl.load_workbook('/Users/saraabreu/Desktop/TRABALHOS/ISEP/PROJETO1/PRJT1_2022-2023_Sched_instance_1.xlsx')
shift_wb = data_wb.worksheets[0]

# Salva a planilha num arquivo temporário
with tempfile.NamedTemporaryFile(delete=False) as temp:
    data_wb.save(temp.name)
    # Lê os dados da planilha em um DataFrame
    shift_data = pd.read_excel(temp.name)

# Remove o arquivo temporário
os.unlink(temp.name)

shifts = {}

for i in range(shift_data.shape[0]):
    shift = shift_data.iloc[i]["Shift"]
    duration = shift_data.iloc[i]["Duration(min)"]
    setup_teams = shift_data.iloc[i]["Setup_teams"]
    log_train = shift_data.iloc[i]["Log_train(packs/hour)"]
    operators = shift_data.iloc[i]["Operators"]

    shifts[shift] = (duration, setup_teams, log_train, operators)

print(shifts)


# initial_data = wb.worksheets[1]
# instance_of_orders = wb.worksheets[2]
# setup_data = wb.worksheets[3]

{1: (480, 1, 120, 30), 2: (480, 2, 120, 30), 3: (480, 1, 120, 30)}